MAIN_PROMPT: |
  1. Register
  2. Login
  3. Quit
  Enter Choice:
MAIN_PROMPT_LENGTH: 3
ADMIN_PROMPT: |
  1.  View User
  2.  View All Users
  3.  Downgrade Premium User
  4.  Ban User
  5.  Unban User
  6.  Ban URL
  7.  Unban URL
  8.  Unban URL for Premium User
  9.  Messages from Users
  10. View History of User
  11. View all History
  12. View Premium Listing of user
  13. View all Premium Listings
  14. Show all banned urls
  15. Show ban url
  16. Exit
  Enter Choice:
ADMIN_PROMPT_LENGTH: 16
MESSAGES_VIEW_PROMPT: |
  VIEWS-
  1. From Premium Users
  2. From Non Premium Users
  3. Message from Particular User
  4. All Messages
  5. Back
  Enter Choice:
MESSAGES_VIEW_PROMPT_LENGTH: 5
MESSAGES_FILTER: |
  1. Old First
  2. Latest
  Enter Choice:
MESSAGES_FILTER_LENGTH: 2
NON_PREMIUM_PROMPT: |
  Press:
  1. Submit Video Link 
  2. Upgrade to Premium
  3. Logout
  Enter choice:
NON_PREMIUM_PROMPT_LENGTH: 3
PREMIUM_PROMPT: |
  Press
  1. Submit Video Link 
  2. Request Your Language
  3. Premium Listing of Banned URL
  4. View My History
  5. View my premium listing
  6. Cancel Subscription
  7. Logout
  Enter choice:
PREMIUM_PROMPT_LENGTH: 7
SECURE_USERNAME_PROMPT: |
  Your username must contain:
  Min. 4 length (can contain letters, numbers, @, _, - , .)
SECURE_PASSWORD_PROMPT: |
  Your password must contain:
  Min. 8 length, one uppercase letter, one lowercase letter, one symbol and one number
SUBMIT_VIDEO_PROMPT: Enter URL (Language - English) or Press 1 to back -
LANGUAGE_PROMPT: Enter Language for Summary -
AFTER_SUBMITTING_URL: |
  1. Save Summary
  2. Save Transcript
  3. Show Video Details
  4. Exit
  Enter Choice:
AFTER_SUBMITTING_URL_LENGTH: 4
UPGRADE_TO_PREMIUM_PROMPT: |
  Plan - Rs. 59 per month
  1. Pay
  2. Back
  Enter Choice:
UPGRADE_TO_PREMIUM_PROMPT_LENGTH: 2
BASIC_USER_INTRO: Current Plan -> Basic User
PREMIUM_USER_INTRO: Current Plan -> Premium User
INVALID_INPUT_PROMPT: Please Select Carefully!
EXITING_PROMPT: Exiting...
APP_INTRO: 'Transcriptor :-> Smart Video, Simply Summarised!!'
APP_OUTRO: Bye! Thanks for using.
ENTER_USERNAME_PROMPT: Enter Username -
ENTER_PASSWORD_PROMPT: Enter Password -
ENTER_URL: Enter URL -
NO_USER_FOUND: No Such User Found
NO_URL_FOUND: No Such Banned URL Found
PROCESSING_PROMPT: Processing...
NUMBERS_ONLY_PROMPT: Numbers only
INVALID_USERNAME_PROMPT: Invalid Username!
INVALID_PASSWORD_PROMPT: Invalid Password!
REGISTRATION_SUCCESS: Registered successfully!
ALREADY_EXIST: | 
  Already registered!!
  Try login!!
VALID_URL: Enter valid url.
ALREADY_BANNED_URL: Already Banned Url
VIDEO_NOT_SUPPORTED: This video is not supported. Please try other videos.
EXHAUSTED_BAN: |
  You have exhausted ban search limits in a day.
  YOU ARE BANNED.
  PLEASE CONTACT ADMIN!!
BANNED_CONTENT: Bad Content
UPGRADED_PREMIUM: You are now upgraded to premium.
DOWNGRADED_PREMIUM: You are downgraded.
ENTER_VALID_CHOICE: Enter valid choice.
BACK: Back..
ANALYSE_TEXT_FAILED: Analyze text failed.
SUMMARY_GENERATION_FAILED: Summary Generation Failed. Try Again!
USER_BANNED: User banned
USER_UNBANNED: User unbanned
URL_BANNED: URL banned
URL_UNBANNED: URL unbanned
PREMIUM_LISTING_DONE: Premium Listing done for
ENTER_MESSAGE: 'Enter Message for admin: '
MESSAGE_SENT: Message sent successfully.
ENTER_URL_FOR_PREMIUMLISTING: 'Enter URL for premium listing: '
ACKNOWLEDGEMENT: Once approved by admin, it'll be added to your premium listing.
NO_DATA_EXIST: No data exists
MESSAGE_TO_ADMIN_FOR_UNBAN: 'Send Message to Admin for Unban: '
MESSAGE_NOT_SENT: Message not sent successfully.
CONFIRM_PROMPT: |
  Are you Sure?
  1. Yes
  2. No 
  Enter Choice:
CONFIRM_PROMPT_LENGTH: 2
ADMIN_USERNAME : admin
ADMIN_PASSWORD : '@Admin1234'
SHORT_UUID_CONSTRAINTS: "123456789"